/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body1Builder {
    //the instance to build
    private Body1 body1;

    /**
     * Default constructor to initialize the instance
     */
    public Body1Builder() {
        body1 = new Body1();
    }

    /**
     * The 10-digit SMS-enabled Ytel number (E.164 format) in which the message is sent.
     */
    public Body1Builder from(String from) {
        body1.setFrom(from);
        return this;
    }

    /**
     * The 10-digit phone number (E.164 format) that will receive the message.
     */
    public Body1Builder to(String to) {
        body1.setTo(to);
        return this;
    }

    /**
     * The body message that is to be sent in the text.
     */
    public Body1Builder body(String body) {
        body1.setBody(body);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required URL once SMS sent.
     */
    public Body1Builder method(String method) {
        body1.setMethod(method);
        return this;
    }

    /**
     * URL that can be requested to receive notification when SMS has Sent. A set of default parameters will be sent here once the SMS is finished.
     */
    public Body1Builder messageStatusCallback(String messageStatusCallback) {
        body1.setMessageStatusCallback(messageStatusCallback);
        return this;
    }

    /**
     * Check's 'to' number can receive sms or not using Carrier API, if wireless = true then text sms is sent, else wireless = false then call is recieved to end user with audible message.
     */
    public Body1Builder smartsms(Boolean smartsms) {
        body1.setSmartsms(smartsms);
        return this;
    }

    /**
     * Delivery reports are a method to tell your system if the message has arrived on the destination phone.
     */
    public Body1Builder deliveryStatus(Boolean deliveryStatus) {
        body1.setDeliveryStatus(deliveryStatus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body1 build() {
        return body1;
    }
}