/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body27Builder {
    //the instance to build
    private Body27 body27;

    /**
     * Default constructor to initialize the instance
     */
    public Body27Builder() {
        body27 = new Body27();
    }

    /**
     * The unique identifier of each call resource
     */
    public Body27Builder callSid(String callSid) {
        body27.setCallSid(callSid);
        return this;
    }

    /**
     * DTMF digits to play to the call. 0-9, #, *, W, or w
     */
    public Body27Builder playDtmf(String playDtmf) {
        body27.setPlayDtmf(playDtmf);
        return this;
    }

    /**
     * The leg of the call DTMF digits should be sent to
     */
    public Body27Builder playDtmfDirection(PlayDtmfDirectionEnum playDtmfDirection) {
        body27.setPlayDtmfDirection(playDtmfDirection);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body27 build() {
        return body27;
    }
}