/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body74Builder {
    //the instance to build
    private Body74 body74;

    /**
     * Default constructor to initialize the instance
     */
    public Body74Builder() {
        body74 = new Body74();
    }

    /**
     * The unique identifier for the voice call.
     */
    public Body74Builder callSid(String callSid) {
        body74.setCallSid(callSid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body74 build() {
        return body74;
    }
}