/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body73Builder {
    //the instance to build
    private Body73 body73;

    /**
     * Default constructor to initialize the instance
     */
    public Body73Builder() {
        body73 = new Body73();
    }

    /**
     * The capability the number supports.
     */
    public Body73Builder numberType(NumberType2Enum numberType) {
        body73.setNumberType(numberType);
        return this;
    }

    /**
     * Specifies the area code for the returned list of available numbers. Only available for North American numbers.
     */
    public Body73Builder areaCode(String areaCode) {
        body73.setAreaCode(areaCode);
        return this;
    }

    /**
     * A positive integer that tells how many number you want to buy at a time.
     */
    public Body73Builder quantity(String quantity) {
        body73.setQuantity(quantity);
        return this;
    }

    /**
     * If desired quantity is unavailable purchase what is available .
     */
    public Body73Builder leftover(String leftover) {
        body73.setLeftover(leftover);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body73 build() {
        return body73;
    }
}