/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body5Builder {
    //the instance to build
    private Body5 body5;

    /**
     * Default constructor to initialize the instance
     */
    public Body5Builder() {
        body5 = new Body5();
    }

    /**
     * Number type either SMS,Voice or all
     */
    public Body5Builder numbertype(Numbertype1Enum numbertype) {
        body5.setNumbertype(numbertype);
        return this;
    }

    /**
     * Specifies the area code for the returned list of available numbers. Only available for North American numbers.
     */
    public Body5Builder areacode(String areacode) {
        body5.setAreacode(areacode);
        return this;
    }

    /**
     * The count of objects to return.
     */
    public Body5Builder pagesize(Integer pagesize) {
        body5.setPagesize(pagesize);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body5 build() {
        return body5;
    }
}