/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body29Builder {
    //the instance to build
    private Body29 body29;

    /**
     * Default constructor to initialize the instance
     */
    public Body29Builder() {
        body29 = new Body29();
    }

    /**
     * The starting point of the list of invalid emails that should be returned.
     */
    public Body29Builder offset(String offset) {
        body29.setOffset(offset);
        return this;
    }

    /**
     * The count of results that should be returned.
     */
    public Body29Builder limit(String limit) {
        body29.setLimit(limit);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body29 build() {
        return body29;
    }
}