/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body67Builder {
    //the instance to build
    private Body67 body67;

    /**
     * Default constructor to initialize the instance
     */
    public Body67Builder() {
        body67 = new Body67();
    }

    /**
     * List of valid Dedicated Short Code to your Ytel account
     */
    public Body67Builder shortcode(String shortcode) {
        body67.setShortcode(shortcode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body67 build() {
        return body67;
    }
}