/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body69Builder {
    //the instance to build
    private Body69 body69;

    /**
     * Default constructor to initialize the instance
     */
    public Body69Builder() {
        body69 = new Body69();
    }

    /**
     * The unique identifier for a sms message.
     */
    public Body69Builder messageSid(String messageSid) {
        body69.setMessageSid(messageSid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body69 build() {
        return body69;
    }
}