/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body7Builder {
    //the instance to build
    private Body7 body7;

    /**
     * Default constructor to initialize the instance
     */
    public Body7Builder() {
        body7 = new Body7();
    }

    /**
     * The unique identifier for a conference object.
     */
    public Body7Builder conferenceSid(String conferenceSid) {
        body7.setConferenceSid(conferenceSid);
        return this;
    }

    /**
     * The unique identifier for a participant object.
     */
    public Body7Builder participantSid(String participantSid) {
        body7.setParticipantSid(participantSid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body7 build() {
        return body7;
    }
}