/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body68Builder {
    //the instance to build
    private Body68 body68;

    /**
     * Default constructor to initialize the instance
     */
    public Body68Builder() {
        body68 = new Body68();
    }

    /**
     * Sub account user first name
     */
    public Body68Builder firstName(String firstName) {
        body68.setFirstName(firstName);
        return this;
    }

    /**
     * sub account user last name
     */
    public Body68Builder lastName(String lastName) {
        body68.setLastName(lastName);
        return this;
    }

    /**
     * Sub account email address
     */
    public Body68Builder email(String email) {
        body68.setEmail(email);
        return this;
    }

    /**
     * Descriptive name of the sub account
     */
    public Body68Builder friendlyName(String friendlyName) {
        body68.setFriendlyName(friendlyName);
        return this;
    }

    /**
     * The password of the sub account.  Please make sure to make as password that is at least 8 characters long, contain a symbol, uppercase and a number.
     */
    public Body68Builder password(String password) {
        body68.setPassword(password);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body68 build() {
        return body68;
    }
}