/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body32Builder {
    //the instance to build
    private Body32 body32;

    /**
     * Default constructor to initialize the instance
     */
    public Body32Builder() {
        body32 = new Body32();
    }

    /**
     * The starting point of the list of spam emails that should be returned.
     */
    public Body32Builder offset(String offset) {
        body32.setOffset(offset);
        return this;
    }

    /**
     * The count of results that should be returned.
     */
    public Body32Builder limit(String limit) {
        body32.setLimit(limit);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body32 build() {
        return body32;
    }
}