/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body34Builder {
    //the instance to build
    private Body34 body34;

    /**
     * Default constructor to initialize the instance
     */
    public Body34Builder() {
        body34 = new Body34();
    }

    /**
     * The SubaccountSid to be deleted
     */
    public Body34Builder subAccountSID(String subAccountSID) {
        body34.setSubAccountSID(subAccountSID);
        return this;
    }

    /**
     * 0 to delete or 1 to merge numbers to parent account.
     */
    public Body34Builder mergeNumber(MergeNumberEnum mergeNumber) {
        body34.setMergeNumber(mergeNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body34 build() {
        return body34;
    }
}