/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body65Builder {
    //the instance to build
    private Body65 body65;

    /**
     * Default constructor to initialize the instance
     */
    public Body65Builder() {
        body65 = new Body65();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body65Builder page(Integer page) {
        body65.setPage(page);
        return this;
    }

    /**
     * Number of individual resources listed in the response per page
     */
    public Body65Builder pagesize(Integer pagesize) {
        body65.setPagesize(pagesize);
        return this;
    }

    /**
     * Only return conferences with the specified FriendlyName
     */
    public Body65Builder friendlyName(String friendlyName) {
        body65.setFriendlyName(friendlyName);
        return this;
    }

    /**
     * Conference created date
     */
    public Body65Builder dateCreated(String dateCreated) {
        body65.setDateCreated(dateCreated);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body65 build() {
        return body65;
    }
}