/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body75Builder {
    //the instance to build
    private Body75 body75;

    /**
     * Default constructor to initialize the instance
     */
    public Body75Builder() {
        body75 = new Body75();
    }

    /**
     * List of valid dedicated shortcode to your Ytel account.
     */
    public Body75Builder shortcode(String shortcode) {
        body75.setShortcode(shortcode);
        return this;
    }

    /**
     * User generated name of the dedicated shortcode.
     */
    public Body75Builder friendlyName(String friendlyName) {
        body75.setFriendlyName(friendlyName);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.
     */
    public Body75Builder callbackMethod(String callbackMethod) {
        body75.setCallbackMethod(callbackMethod);
        return this;
    }

    /**
     * URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
     */
    public Body75Builder callbackUrl(String callbackUrl) {
        body75.setCallbackUrl(callbackUrl);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required FallbackUrl once call connects.
     */
    public Body75Builder fallbackMethod(String fallbackMethod) {
        body75.setFallbackMethod(fallbackMethod);
        return this;
    }

    /**
     * URL used if any errors occur during execution of InboundXML or at initial request of the required Url provided with the POST.
     */
    public Body75Builder fallbackUrl(String fallbackUrl) {
        body75.setFallbackUrl(fallbackUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body75 build() {
        return body75;
    }
}