/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body6Builder {
    //the instance to build
    private Body6 body6;

    /**
     * Default constructor to initialize the instance
     */
    public Body6Builder() {
        body6 = new Body6();
    }

    /**
     * ID of the active conference
     */
    public Body6Builder conferenceSid(String conferenceSid) {
        body6.setConferenceSid(conferenceSid);
        return this;
    }

    /**
     * ID of an active participant
     */
    public Body6Builder participantSid(String participantSid) {
        body6.setParticipantSid(participantSid);
        return this;
    }

    /**
     * Mute a participant
     */
    public Body6Builder muted(Boolean muted) {
        body6.setMuted(muted);
        return this;
    }

    /**
     * Make it so a participant cant hear
     */
    public Body6Builder deaf(Boolean deaf) {
        body6.setDeaf(deaf);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body6 build() {
        return body6;
    }
}