/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body38Builder {
    //the instance to build
    private Body38 body38;

    /**
     * Default constructor to initialize the instance
     */
    public Body38Builder() {
        body38 = new Body38();
    }

    /**
     * Only list messages sent from this Short Code
     */
    public Body38Builder shortcode(String shortcode) {
        body38.setShortcode(shortcode);
        return this;
    }

    /**
     * Only list messages sent to this number
     */
    public Body38Builder to(String to) {
        body38.setTo(to);
        return this;
    }

    /**
     * Only list messages sent with the specified date
     */
    public Body38Builder dateSent(String dateSent) {
        body38.setDateSent(dateSent);
        return this;
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body38Builder page(Integer page) {
        body38.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public Body38Builder pageSize(Integer pageSize) {
        body38.setPageSize(pageSize);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body38 build() {
        return body38;
    }
}