/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body59 
        implements java.io.Serializable {
    private static final long serialVersionUID = -76937280139562673L;
    private String keywordid;
    /** GETTER
     * The unique identifier of each keyword
     */
    @JsonGetter("Keywordid")
    public String getKeywordid ( ) { 
        return this.keywordid;
    }
    
    /** SETTER
     * The unique identifier of each keyword
     */
    @JsonSetter("Keywordid")
    public void setKeywordid (String value) { 
        this.keywordid = value;
    }
 
}
