/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body72 
        implements java.io.Serializable {
    private static final long serialVersionUID = -79873758931424641L;
    private String phonenumber;
    /** GETTER
     * Specifies the multiple phone numbers for check updated spamscore .
     */
    @JsonGetter("Phonenumber")
    public String getPhonenumber ( ) { 
        return this.phonenumber;
    }
    
    /** SETTER
     * Specifies the multiple phone numbers for check updated spamscore .
     */
    @JsonSetter("Phonenumber")
    public void setPhonenumber (String value) { 
        this.phonenumber = value;
    }
 
}
