/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body4Builder {
    //the instance to build
    private Body4 body4;

    /**
     * Default constructor to initialize the instance
     */
    public Body4Builder() {
        body4 = new Body4();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body4Builder page(Integer page) {
        body4.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public Body4Builder pageSize(Integer pageSize) {
        body4.setPageSize(pageSize);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body4 build() {
        return body4;
    }
}