/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body31Builder {
    //the instance to build
    private Body31 body31;

    /**
     * Default constructor to initialize the instance
     */
    public Body31Builder() {
        body31 = new Body31();
    }

    /**
     * The starting point of the list of bounced emails that should be returned.
     */
    public Body31Builder offset(String offset) {
        body31.setOffset(offset);
        return this;
    }

    /**
     * The count of results that should be returned.
     */
    public Body31Builder limit(String limit) {
        body31.setLimit(limit);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body31 build() {
        return body31;
    }
}