/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body10Builder {
    //the instance to build
    private Body10 body10;

    /**
     * Default constructor to initialize the instance
     */
    public Body10Builder() {
        body10 = new Body10();
    }

    /**
     * The unique identifier for a recording object.
     */
    public Body10Builder recordingSid(String recordingSid) {
        body10.setRecordingSid(recordingSid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body10 build() {
        return body10;
    }
}