/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body21Builder {
    //the instance to build
    private Body21 body21;

    /**
     * Default constructor to initialize the instance
     */
    public Body21Builder() {
        body21 = new Body21();
    }

    /**
     * A valid address that will receive the email. Multiple addresses can be separated by using commas.
     */
    public Body21Builder to(String to) {
        body21.setTo(to);
        return this;
    }

    /**
     * Specifies the type of email to be sent
     */
    public Body21Builder type(TypeEnum type) {
        body21.setType(type);
        return this;
    }

    /**
     * The subject of the mail. Must be a valid string.
     */
    public Body21Builder subject(String subject) {
        body21.setSubject(subject);
        return this;
    }

    /**
     * The email message that is to be sent in the text.
     */
    public Body21Builder message(String message) {
        body21.setMessage(message);
        return this;
    }

    /**
     * A valid address that will send the email.
     */
    public Body21Builder from(String from) {
        body21.setFrom(from);
        return this;
    }

    /**
     * Carbon copy. A valid address that will receive the email. Multiple addresses can be separated by using commas.
     */
    public Body21Builder cc(String cc) {
        body21.setCc(cc);
        return this;
    }

    /**
     * Blind carbon copy. A valid address that will receive the email. Multiple addresses can be separated by using commas.
     */
    public Body21Builder bcc(String bcc) {
        body21.setBcc(bcc);
        return this;
    }

    /**
     * A file that is attached to the email. Must be less than 7 MB in size.
     */
    public Body21Builder attachment(String attachment) {
        body21.setAttachment(attachment);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body21 build() {
        return body21;
    }
}