/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body35 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5472762375040697394L;
    private String subAccountSID;
    private ActivateEnum activate;
    /** GETTER
     * The SubaccountSid to be activated or suspended
     */
    @JsonGetter("SubAccountSID")
    public String getSubAccountSID ( ) { 
        return this.subAccountSID;
    }
    
    /** SETTER
     * The SubaccountSid to be activated or suspended
     */
    @JsonSetter("SubAccountSID")
    public void setSubAccountSID (String value) { 
        this.subAccountSID = value;
    }
 
    /** GETTER
     * 0 to suspend or 1 to activate
     */
    @JsonGetter("Activate")
    public ActivateEnum getActivate ( ) { 
        return this.activate;
    }
    
    /** SETTER
     * 0 to suspend or 1 to activate
     */
    @JsonSetter("Activate")
    public void setActivate (ActivateEnum value) { 
        this.activate = value;
    }
 
}
