/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body64Builder {
    //the instance to build
    private Body64 body64;

    /**
     * Default constructor to initialize the instance
     */
    public Body64Builder() {
        body64 = new Body64();
    }

    /**
     * The unique identifier for a conference.
     */
    public Body64Builder conferenceSid(String conferenceSid) {
        body64.setConferenceSid(conferenceSid);
        return this;
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body64Builder page(Integer page) {
        body64.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public Body64Builder pagesize(Integer pagesize) {
        body64.setPagesize(pagesize);
        return this;
    }

    /**
     * Specifies if participant should be muted.
     */
    public Body64Builder muted(Boolean muted) {
        body64.setMuted(muted);
        return this;
    }

    /**
     * Specifies if the participant should hear audio in the conference.
     */
    public Body64Builder deaf(Boolean deaf) {
        body64.setDeaf(deaf);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body64 build() {
        return body64;
    }
}