/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body54Builder {
    //the instance to build
    private Body54 body54;

    /**
     * Default constructor to initialize the instance
     */
    public Body54Builder() {
        body54 = new Body54();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body54Builder page(Integer page) {
        body54.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public Body54Builder pageSize(Integer pageSize) {
        body54.setPageSize(pageSize);
        return this;
    }

    /**
     * Filter SMS message objects from this valid 10-digit phone number (E.164 format).
     */
    public Body54Builder from(String from) {
        body54.setFrom(from);
        return this;
    }

    /**
     * Filter SMS message objects to this valid 10-digit phone number (E.164 format).
     */
    public Body54Builder to(String to) {
        body54.setTo(to);
        return this;
    }

    /**
     * Filter sms message objects by this date.
     */
    public Body54Builder dateSent(String dateSent) {
        body54.setDateSent(dateSent);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body54 build() {
        return body54;
    }
}