/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body11Builder {
    //the instance to build
    private Body11 body11;

    /**
     * Default constructor to initialize the instance
     */
    public Body11Builder() {
        body11 = new Body11();
    }

    /**
     * URL pointing to the location of the audio file that is to be transcribed.
     */
    public Body11Builder audiourl(String audiourl) {
        body11.setAudiourl(audiourl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body11 build() {
        return body11;
    }
}