/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body24Builder {
    //the instance to build
    private Body24 body24;

    /**
     * Default constructor to initialize the instance
     */
    public Body24Builder() {
        body24 = new Body24();
    }

    /**
     * The unique identifier for the in-progress voice call.
     */
    public Body24Builder callSid(String callSid) {
        body24.setCallSid(callSid);
        return this;
    }

    /**
     * The direction the audio effect should be placed on. If IN, the effects will occur on the incoming audio stream. If OUT, the effects will occur on the outgoing audio stream.
     */
    public Body24Builder audioDirection(AudioDirectionEnum audioDirection) {
        body24.setAudioDirection(audioDirection);
        return this;
    }

    /**
     * Set the pitch in semitone (half-step) intervals. Value between -14 and 14
     */
    public Body24Builder pitchSemiTones(Double pitchSemiTones) {
        body24.setPitchSemiTones(pitchSemiTones);
        return this;
    }

    /**
     * Set the pitch in octave intervals.. Value between -1 and 1
     */
    public Body24Builder pitchOctaves(Double pitchOctaves) {
        body24.setPitchOctaves(pitchOctaves);
        return this;
    }

    /**
     * Set the pitch (lowness/highness) of the audio. The higher the value, the higher the pitch. Value greater than 0
     */
    public Body24Builder pitch(Double pitch) {
        body24.setPitch(pitch);
        return this;
    }

    /**
     * Set the rate for audio. The lower the value, the lower the rate. value greater than 0
     */
    public Body24Builder rate(Double rate) {
        body24.setRate(rate);
        return this;
    }

    /**
     * Set the tempo (speed) of the audio. A higher value denotes a faster tempo. Value greater than 0
     */
    public Body24Builder tempo(Double tempo) {
        body24.setTempo(tempo);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body24 build() {
        return body24;
    }
}