/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body18Builder {
    //the instance to build
    private Body18 body18;

    /**
     * Default constructor to initialize the instance
     */
    public Body18Builder() {
        body18 = new Body18();
    }

    /**
     * The email address to be remove from the blocked list.
     */
    public Body18Builder email(String email) {
        body18.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body18 build() {
        return body18;
    }
}