/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body13Builder {
    //the instance to build
    private Body13 body13;

    /**
     * Default constructor to initialize the instance
     */
    public Body13Builder() {
        body13 = new Body13();
    }

    /**
     * The unique identifier for a recording.
     */
    public Body13Builder recordingsid(String recordingsid) {
        body13.setRecordingsid(recordingsid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body13 build() {
        return body13;
    }
}