/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body18 
        implements java.io.Serializable {
    private static final long serialVersionUID = 93794946829320330L;
    private String email;
    /** GETTER
     * The email address to be remove from the blocked list.
     */
    @JsonGetter("Email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * The email address to be remove from the blocked list.
     */
    @JsonSetter("Email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
}
