/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body52Builder {
    //the instance to build
    private Body52 body52;

    /**
     * Default constructor to initialize the instance
     */
    public Body52Builder() {
        body52 = new Body52();
    }

    /**
     * Your dedicated shortcode
     */
    public Body52Builder shortcode(int shortcode) {
        body52.setShortcode(shortcode);
        return this;
    }

    /**
     * The number to send your SMS to
     */
    public Body52Builder to(double to) {
        body52.setTo(to);
        return this;
    }

    /**
     * The body of your message
     */
    public Body52Builder body(String body) {
        body52.setBody(body);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required URL once the Short Code message is sent.GET or POST
     */
    public Body52Builder method(String method) {
        body52.setMethod(method);
        return this;
    }

    /**
     * URL that can be requested to receive notification when Short Code message was sent.
     */
    public Body52Builder messagestatuscallback(String messagestatuscallback) {
        body52.setMessagestatuscallback(messagestatuscallback);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body52 build() {
        return body52;
    }
}