/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body34 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1171877584994936967L;
    private String subAccountSID;
    private MergeNumberEnum mergeNumber;
    /** GETTER
     * The SubaccountSid to be deleted
     */
    @JsonGetter("SubAccountSID")
    public String getSubAccountSID ( ) { 
        return this.subAccountSID;
    }
    
    /** SETTER
     * The SubaccountSid to be deleted
     */
    @JsonSetter("SubAccountSID")
    public void setSubAccountSID (String value) { 
        this.subAccountSID = value;
    }
 
    /** GETTER
     * 0 to delete or 1 to merge numbers to parent account.
     */
    @JsonGetter("MergeNumber")
    public MergeNumberEnum getMergeNumber ( ) { 
        return this.mergeNumber;
    }
    
    /** SETTER
     * 0 to delete or 1 to merge numbers to parent account.
     */
    @JsonSetter("MergeNumber")
    public void setMergeNumber (MergeNumberEnum value) { 
        this.mergeNumber = value;
    }
 
}
