/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body49Builder {
    //the instance to build
    private Body49 body49;

    /**
     * Default constructor to initialize the instance
     */
    public Body49Builder() {
        body49 = new Body49();
    }

    /**
     * Filter usage results by product type.
     */
    public Body49Builder productCode(ProductCodeEnum productCode) {
        body49.setProductCode(productCode);
        return this;
    }

    /**
     * Filter usage objects by start date.
     */
    public Body49Builder startDate(String startDate) {
        body49.setStartDate(startDate);
        return this;
    }

    /**
     * Filter usage objects by end date.
     */
    public Body49Builder endDate(String endDate) {
        body49.setEndDate(endDate);
        return this;
    }

    /**
     * Will include all subaccount usage data
     */
    public Body49Builder includeSubAccounts(String includeSubAccounts) {
        body49.setIncludeSubAccounts(includeSubAccounts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body49 build() {
        return body49;
    }
}