/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body51Builder {
    //the instance to build
    private Body51 body51;

    /**
     * Default constructor to initialize the instance
     */
    public Body51Builder() {
        body51 = new Body51();
    }

    /**
     * The unique identifier for a conference object.
     */
    public Body51Builder conferenceSid(String conferenceSid) {
        body51.setConferenceSid(conferenceSid);
        return this;
    }

    /**
     * The phone number of the participant to be added.
     */
    public Body51Builder participantNumber(String participantNumber) {
        body51.setParticipantNumber(participantNumber);
        return this;
    }

    /**
     * Specifies if participant should be muted.
     */
    public Body51Builder muted(Boolean muted) {
        body51.setMuted(muted);
        return this;
    }

    /**
     * Specifies if the participant should hear audio in the conference.
     */
    public Body51Builder deaf(Boolean deaf) {
        body51.setDeaf(deaf);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body51 build() {
        return body51;
    }
}