/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body74 
        implements java.io.Serializable {
    private static final long serialVersionUID = -7115593291038354L;
    private String callSid;
    /** GETTER
     * The unique identifier for the voice call.
     */
    @JsonGetter("callSid")
    public String getCallSid ( ) { 
        return this.callSid;
    }
    
    /** SETTER
     * The unique identifier for the voice call.
     */
    @JsonSetter("callSid")
    public void setCallSid (String value) { 
        this.callSid = value;
    }
 
}
