/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body56Builder {
    //the instance to build
    private Body56 body56;

    /**
     * Default constructor to initialize the instance
     */
    public Body56Builder() {
        body56 = new Body56();
    }

    /**
     * The unique identifier for a conference object.
     */
    public Body56Builder conferenceSid(String conferenceSid) {
        body56.setConferenceSid(conferenceSid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body56 build() {
        return body56;
    }
}