/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body28Builder {
    //the instance to build
    private Body28 body28;

    /**
     * Default constructor to initialize the instance
     */
    public Body28Builder() {
        body28 = new Body28();
    }

    /**
     * The unique identifier for voice call that is in progress.
     */
    public Body28Builder callSid(String callSid) {
        body28.setCallSid(callSid);
        return this;
    }

    /**
     * URL the in-progress call will be redirected to
     */
    public Body28Builder url(String url) {
        body28.setUrl(url);
        return this;
    }

    /**
     * The method used to request the above Url parameter
     */
    public Body28Builder method(String method) {
        body28.setMethod(method);
        return this;
    }

    /**
     * Status to set the in-progress call to
     */
    public Body28Builder status(Status1Enum status) {
        body28.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body28 build() {
        return body28;
    }
}