/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body59Builder {
    //the instance to build
    private Body59 body59;

    /**
     * Default constructor to initialize the instance
     */
    public Body59Builder() {
        body59 = new Body59();
    }

    /**
     * The unique identifier of each keyword
     */
    public Body59Builder keywordid(String keywordid) {
        body59.setKeywordid(keywordid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body59 build() {
        return body59;
    }
}