/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body25Builder {
    //the instance to build
    private Body25 body25;

    /**
     * Default constructor to initialize the instance
     */
    public Body25Builder() {
        body25 = new Body25();
    }

    /**
     * A valid email address that is to be remove from the unsubscribe list.
     */
    public Body25Builder email(String email) {
        body25.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body25 build() {
        return body25;
    }
}