/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body2Builder {
    //the instance to build
    private Body2 body2;

    /**
     * Default constructor to initialize the instance
     */
    public Body2Builder() {
        body2 = new Body2();
    }

    /**
     * The unique identifier for a template object
     */
    public Body2Builder templateId(UUID templateId) {
        body2.setTemplateId(templateId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body2 build() {
        return body2;
    }
}