/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body63Builder {
    //the instance to build
    private Body63 body63;

    /**
     * Default constructor to initialize the instance
     */
    public Body63Builder() {
        body63 = new Body63();
    }

    /**
     * List of valid shortcode to your Ytel account
     */
    public Body63Builder shortcode(String shortcode) {
        body63.setShortcode(shortcode);
        return this;
    }

    /**
     * User generated name of the shortcode
     */
    public Body63Builder friendlyName(String friendlyName) {
        body63.setFriendlyName(friendlyName);
        return this;
    }

    /**
     * URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
     */
    public Body63Builder callbackUrl(String callbackUrl) {
        body63.setCallbackUrl(callbackUrl);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.
     */
    public Body63Builder callbackMethod(String callbackMethod) {
        body63.setCallbackMethod(callbackMethod);
        return this;
    }

    /**
     * URL used if any errors occur during execution of InboundXML or at initial request of the required Url provided with the POST.
     */
    public Body63Builder fallbackUrl(String fallbackUrl) {
        body63.setFallbackUrl(fallbackUrl);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required FallbackUrl once call connects.
     */
    public Body63Builder fallbackUrlMethod(String fallbackUrlMethod) {
        body63.setFallbackUrlMethod(fallbackUrlMethod);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body63 build() {
        return body63;
    }
}