/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body70Builder {
    //the instance to build
    private Body70 body70;

    /**
     * Default constructor to initialize the instance
     */
    public Body70Builder() {
        body70 = new Body70();
    }

    /**
     * Which page of the overall response will be returned. Page indexing starts at 1.
     */
    public Body70Builder page(Integer page) {
        body70.setPage(page);
        return this;
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body70Builder pageSize(Integer pageSize) {
        body70.setPageSize(pageSize);
        return this;
    }

    /**
     * The capability supported by the number.Number type either SMS,Voice or all
     */
    public Body70Builder numberType(NumberTypeEnum numberType) {
        body70.setNumberType(numberType);
        return this;
    }

    /**
     * A human-readable label added to the number object.
     */
    public Body70Builder friendlyName(String friendlyName) {
        body70.setFriendlyName(friendlyName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body70 build() {
        return body70;
    }
}