/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body9Builder {
    //the instance to build
    private Body9 body9;

    /**
     * Default constructor to initialize the instance
     */
    public Body9Builder() {
        body9 = new Body9();
    }

    /**
     * The unique identifier for a transcription object.
     */
    public Body9Builder transcriptionsid(String transcriptionsid) {
        body9.setTranscriptionsid(transcriptionsid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body9 build() {
        return body9;
    }
}