/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body66Builder {
    //the instance to build
    private Body66 body66;

    /**
     * Default constructor to initialize the instance
     */
    public Body66Builder() {
        body66 = new Body66();
    }

    /**
     * A valid 10-digit Ytel number (E.164 format).
     */
    public Body66Builder phonenumber(String phonenumber) {
        body66.setPhonenumber(phonenumber);
        return this;
    }

    /**
     * A specific Accountsid from where Number is getting transfer.
     */
    public Body66Builder fromaccountsid(String fromaccountsid) {
        body66.setFromaccountsid(fromaccountsid);
        return this;
    }

    /**
     * A specific Accountsid to which Number is getting transfer.
     */
    public Body66Builder toaccountsid(String toaccountsid) {
        body66.setToaccountsid(toaccountsid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body66 build() {
        return body66;
    }
}