/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body60Builder {
    //the instance to build
    private Body60 body60;

    /**
     * Default constructor to initialize the instance
     */
    public Body60Builder() {
        body60 = new Body60();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body60Builder page(Integer page) {
        body60.setPage(page);
        return this;
    }

    /**
     * Number of individual resources listed in the response per page
     */
    public Body60Builder pagesize(Integer pagesize) {
        body60.setPagesize(pagesize);
        return this;
    }

    /**
     * Only list keywords of keyword
     */
    public Body60Builder keyword(String keyword) {
        body60.setKeyword(keyword);
        return this;
    }

    /**
     * Only list keywords of shortcode
     */
    public Body60Builder shortcode(Integer shortcode) {
        body60.setShortcode(shortcode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body60 build() {
        return body60;
    }
}