/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body72Builder {
    //the instance to build
    private Body72 body72;

    /**
     * Default constructor to initialize the instance
     */
    public Body72Builder() {
        body72 = new Body72();
    }

    /**
     * Specifies the multiple phone numbers for check updated spamscore .
     */
    public Body72Builder phonenumber(String phonenumber) {
        body72.setPhonenumber(phonenumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body72 build() {
        return body72;
    }
}