/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body45Builder {
    //the instance to build
    private Body45 body45;

    /**
     * Default constructor to initialize the instance
     */
    public Body45Builder() {
        body45 = new Body45();
    }

    /**
     * A valid 10-digit number (E.164 format).
     */
    public Body45Builder phoneNumber(String phoneNumber) {
        body45.setPhoneNumber(phoneNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body45 build() {
        return body45;
    }
}