/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body76Builder {
    //the instance to build
    private Body76 body76;

    /**
     * Default constructor to initialize the instance
     */
    public Body76Builder() {
        body76 = new Body76();
    }

    /**
     * Only list Short Code Assignment sent from this Short Code
     */
    public Body76Builder shortcode(String shortcode) {
        body76.setShortcode(shortcode);
        return this;
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body76Builder page(String page) {
        body76.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public Body76Builder pagesize(String pagesize) {
        body76.setPagesize(pagesize);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body76 build() {
        return body76;
    }
}