/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body11 
        implements java.io.Serializable {
    private static final long serialVersionUID = -54664445155684701L;
    private String audiourl;
    /** GETTER
     * URL pointing to the location of the audio file that is to be transcribed.
     */
    @JsonGetter("audiourl")
    public String getAudiourl ( ) { 
        return this.audiourl;
    }
    
    /** SETTER
     * URL pointing to the location of the audio file that is to be transcribed.
     */
    @JsonSetter("audiourl")
    public void setAudiourl (String value) { 
        this.audiourl = value;
    }
 
}
