/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body23Builder {
    //the instance to build
    private Body23 body23;

    /**
     * Default constructor to initialize the instance
     */
    public Body23Builder() {
        body23 = new Body23();
    }

    /**
     * The unique identifier of each call resource
     */
    public Body23Builder callSid(String callSid) {
        body23.setCallSid(callSid);
        return this;
    }

    /**
     * Set true to initiate recording or false to terminate recording
     */
    public Body23Builder record(boolean record) {
        body23.setRecord(record);
        return this;
    }

    /**
     * The leg of the call to record
     */
    public Body23Builder direction(DirectionEnum direction) {
        body23.setDirection(direction);
        return this;
    }

    /**
     * Time in seconds the recording duration should not exceed
     */
    public Body23Builder timeLimit(Integer timeLimit) {
        body23.setTimeLimit(timeLimit);
        return this;
    }

    /**
     * URL consulted after the recording completes
     */
    public Body23Builder callBackUrl(String callBackUrl) {
        body23.setCallBackUrl(callBackUrl);
        return this;
    }

    /**
     * Format of the recording file. Can be .mp3 or .wav
     */
    public Body23Builder fileformat(FileformatEnum fileformat) {
        body23.setFileformat(fileformat);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body23 build() {
        return body23;
    }
}