/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body42Builder {
    //the instance to build
    private Body42 body42;

    /**
     * Default constructor to initialize the instance
     */
    public Body42Builder() {
        body42 = new Body42();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body42Builder page(Integer page) {
        body42.setPage(page);
        return this;
    }

    /**
     * Number of individual resources listed in the response per page
     */
    public Body42Builder pageSize(Integer pageSize) {
        body42.setPageSize(pageSize);
        return this;
    }

    /**
     * Filter calls that were sent to this 10-digit number (E.164 format).
     */
    public Body42Builder to(String to) {
        body42.setTo(to);
        return this;
    }

    /**
     * Filter calls that were sent from this 10-digit number (E.164 format).
     */
    public Body42Builder from(String from) {
        body42.setFrom(from);
        return this;
    }

    /**
     * Return calls that are from a specified date.
     */
    public Body42Builder dateCreated(String dateCreated) {
        body42.setDateCreated(dateCreated);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body42 build() {
        return body42;
    }
}