/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body61Builder {
    //the instance to build
    private Body61 body61;

    /**
     * Default constructor to initialize the instance
     */
    public Body61Builder() {
        body61 = new Body61();
    }

    /**
     * List of valid Shortcode to your Ytel account
     */
    public Body61Builder shortcode(String shortcode) {
        body61.setShortcode(shortcode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body61 build() {
        return body61;
    }
}