/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body71Builder {
    //the instance to build
    private Body71 body71;

    /**
     * Default constructor to initialize the instance
     */
    public Body71Builder() {
        body71 = new Body71();
    }

    /**
     * A valid comma(,) separated Ytel numbers. (E.164 format).
     */
    public Body71Builder phoneNumber(String phoneNumber) {
        body71.setPhoneNumber(phoneNumber);
        return this;
    }

    /**
     * The URL returning InboundXML incoming calls should execute when connected.
     */
    public Body71Builder voiceUrl(String voiceUrl) {
        body71.setVoiceUrl(voiceUrl);
        return this;
    }

    /**
     * A human-readable value for labeling the number.
     */
    public Body71Builder friendlyName(String friendlyName) {
        body71.setFriendlyName(friendlyName);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the VoiceUrl once incoming call connects.
     */
    public Body71Builder voiceMethod(String voiceMethod) {
        body71.setVoiceMethod(voiceMethod);
        return this;
    }

    /**
     * URL used if any errors occur during execution of InboundXML on a call or at initial request of the voice url
     */
    public Body71Builder voiceFallbackUrl(String voiceFallbackUrl) {
        body71.setVoiceFallbackUrl(voiceFallbackUrl);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the VoiceFallbackUrl once incoming call connects.
     */
    public Body71Builder voiceFallbackMethod(String voiceFallbackMethod) {
        body71.setVoiceFallbackMethod(voiceFallbackMethod);
        return this;
    }

    /**
     * URL that can be requested to receive notification when and how incoming call has ended.
     */
    public Body71Builder hangupCallback(String hangupCallback) {
        body71.setHangupCallback(hangupCallback);
        return this;
    }

    /**
     * The HTTP method Ytel will use when requesting the HangupCallback URL.
     */
    public Body71Builder hangupCallbackMethod(String hangupCallbackMethod) {
        body71.setHangupCallbackMethod(hangupCallbackMethod);
        return this;
    }

    /**
     * URL that can be used to monitor the phone number.
     */
    public Body71Builder heartbeatUrl(String heartbeatUrl) {
        body71.setHeartbeatUrl(heartbeatUrl);
        return this;
    }

    /**
     * The HTTP method Ytel will use when requesting the HeartbeatUrl.
     */
    public Body71Builder heartbeatMethod(String heartbeatMethod) {
        body71.setHeartbeatMethod(heartbeatMethod);
        return this;
    }

    /**
     * URL requested when an SMS is received.
     */
    public Body71Builder smsUrl(String smsUrl) {
        body71.setSmsUrl(smsUrl);
        return this;
    }

    /**
     * The HTTP method Ytel will use when requesting the SmsUrl.
     */
    public Body71Builder smsMethod(String smsMethod) {
        body71.setSmsMethod(smsMethod);
        return this;
    }

    /**
     * URL used if any errors occur during execution of InboundXML from an SMS or at initial request of the SmsUrl.
     */
    public Body71Builder smsFallbackUrl(String smsFallbackUrl) {
        body71.setSmsFallbackUrl(smsFallbackUrl);
        return this;
    }

    /**
     * The HTTP method Ytel will use when URL requested if the SmsUrl is not available.
     */
    public Body71Builder smsFallbackMethod(String smsFallbackMethod) {
        body71.setSmsFallbackMethod(smsFallbackMethod);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body71 build() {
        return body71;
    }
}