/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body44Builder {
    //the instance to build
    private Body44 body44;

    /**
     * Default constructor to initialize the instance
     */
    public Body44Builder() {
        body44 = new Body44();
    }

    /**
     * A valid email address that is to be remove from the invalid email list.
     */
    public Body44Builder email(String email) {
        body44.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body44 build() {
        return body44;
    }
}