/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body36Builder {
    //the instance to build
    private Body36 body36;

    /**
     * Default constructor to initialize the instance
     */
    public Body36Builder() {
        body36 = new Body36();
    }

    /**
     * Filter account information based on date.
     */
    public Body36Builder date(String date) {
        body36.setDate(date);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body36 build() {
        return body36;
    }
}