/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body46Builder {
    //the instance to build
    private Body46 body46;

    /**
     * Default constructor to initialize the instance
     */
    public Body46Builder() {
        body46 = new Body46();
    }

    /**
     * The unique identifier for the voice call.
     */
    public Body46Builder callsid(String callsid) {
        body46.setCallsid(callsid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body46 build() {
        return body46;
    }
}