/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Body36 
        implements java.io.Serializable {
    private static final long serialVersionUID = -65624406354806772L;
    private String date;
    /** GETTER
     * Filter account information based on date.
     */
    @JsonGetter("Date")
    public String getDate ( ) { 
        return this.date;
    }
    
    /** SETTER
     * Filter account information based on date.
     */
    @JsonSetter("Date")
    public void setDate (String value) { 
        this.date = value;
    }
 
}
