/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body12Builder {
    //the instance to build
    private Body12 body12;

    /**
     * Default constructor to initialize the instance
     */
    public Body12Builder() {
        body12 = new Body12();
    }

    /**
     * The unique identifier for the recording.
     */
    public Body12Builder recordingsid(String recordingsid) {
        body12.setRecordingsid(recordingsid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body12 build() {
        return body12;
    }
}