/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body40Builder {
    //the instance to build
    private Body40 body40;

    /**
     * Default constructor to initialize the instance
     */
    public Body40Builder() {
        body40 = new Body40();
    }

    /**
     * The Short Code number that is the sender of this message
     */
    public Body40Builder shortcode(String shortcode) {
        body40.setShortcode(shortcode);
        return this;
    }

    /**
     * A valid 10-digit number that should receive the message
     */
    public Body40Builder to(String to) {
        body40.setTo(to);
        return this;
    }

    /**
     * The unique identifier for the template used for the message
     */
    public Body40Builder templateid(UUID templateid) {
        body40.setTemplateid(templateid);
        return this;
    }

    /**
     * format of your data, example: {companyname}:test,{otpcode}:1234
     */
    public Body40Builder data(String data) {
        body40.setData(data);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required URL once the Short Code message is sent.
     */
    public Body40Builder method(String method) {
        body40.setMethod(method);
        return this;
    }

    /**
     * URL that can be requested to receive notification when Short Code message was sent.
     */
    public Body40Builder messageStatusCallback(String messageStatusCallback) {
        body40.setMessageStatusCallback(messageStatusCallback);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body40 build() {
        return body40;
    }
}