/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body20Builder {
    //the instance to build
    private Body20 body20;

    /**
     * Default constructor to initialize the instance
     */
    public Body20Builder() {
        body20 = new Body20();
    }

    /**
     * The unique identifier of each conference resource
     */
    public Body20Builder conferenceSid(String conferenceSid) {
        body20.setConferenceSid(conferenceSid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body20 build() {
        return body20;
    }
}