/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body14Builder {
    //the instance to build
    private Body14 body14;

    /**
     * Default constructor to initialize the instance
     */
    public Body14Builder() {
        body14 = new Body14();
    }

    /**
     * A valid 10-digit Ytel number (E.164 format).
     */
    public Body14Builder phoneNumber(String phoneNumber) {
        body14.setPhoneNumber(phoneNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body14 build() {
        return body14;
    }
}