/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body17Builder {
    //the instance to build
    private Body17 body17;

    /**
     * Default constructor to initialize the instance
     */
    public Body17Builder() {
        body17 = new Body17();
    }

    /**
     * A valid email address that is to be remove from the spam list.
     */
    public Body17Builder email(String email) {
        body17.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body17 build() {
        return body17;
    }
}