/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.models;

import java.util.*;

public class Body62Builder {
    //the instance to build
    private Body62 body62;

    /**
     * Default constructor to initialize the instance
     */
    public Body62Builder() {
        body62 = new Body62();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public Body62Builder page(Integer page) {
        body62.setPage(page);
        return this;
    }

    /**
     * Number of individual resources listed in the response per page
     */
    public Body62Builder pagesize(Integer pagesize) {
        body62.setPagesize(pagesize);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Body62 build() {
        return body62;
    }
}